set -e
true
true
/data/homezvol0/itamburi/.conda/envs/spades/bin/spades-core /dfs6/pub/itamburi/ee283/week4/A4/assembly/K21/configs/config.info /dfs6/pub/itamburi/ee283/week4/A4/assembly/K21/configs/isolate_mode.info
/data/homezvol0/itamburi/.conda/envs/spades/bin/spades-core /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/configs/config.info /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/configs/isolate_mode.info
/data/homezvol0/itamburi/.conda/envs/deeptools/bin/python /data/homezvol0/itamburi/.conda/envs/spades/share/spades/spades_pipeline/scripts/copy_files.py /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/before_rr.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/before_rr.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/assembly_graph_after_simplification.gfa /dfs6/pub/itamburi/ee283/week4/A4/assembly/assembly_graph_after_simplification.gfa /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/final_contigs.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/contigs.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/first_pe_contigs.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/first_pe_contigs.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/strain_graph.gfa /dfs6/pub/itamburi/ee283/week4/A4/assembly/strain_graph.gfa /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/scaffolds.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/scaffolds.fasta /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/scaffolds.paths /dfs6/pub/itamburi/ee283/week4/A4/assembly/scaffolds.paths /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/assembly_graph_with_scaffolds.gfa /dfs6/pub/itamburi/ee283/week4/A4/assembly/assembly_graph_with_scaffolds.gfa /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/assembly_graph.fastg /dfs6/pub/itamburi/ee283/week4/A4/assembly/assembly_graph.fastg /dfs6/pub/itamburi/ee283/week4/A4/assembly/K33/final_contigs.paths /dfs6/pub/itamburi/ee283/week4/A4/assembly/contigs.paths
true
/data/homezvol0/itamburi/.conda/envs/deeptools/bin/python /data/homezvol0/itamburi/.conda/envs/spades/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /dfs6/pub/itamburi/ee283/week4/A4/assembly/scaffolds.fasta --misc_dir /dfs6/pub/itamburi/ee283/week4/A4/assembly/misc --threshold_for_breaking_scaffolds 3
true
